name: go-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  get-go-version:
    name: Get Go Version
    runs-on: ubuntu-latest
    outputs:
      go_version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ENGINEERING_GITHUB_PERSONAL_ACCESS_TOKEN }}

      - name: Get Go Version from go.mod
        id: get-version
        run: |
          # Extract the Go version from go.mod
          GO_VERSION=$(grep -oP '^go \K[0-9]+\.[0-9]+' go.mod)
          echo "Go Version: $GO_VERSION"
          echo "version=$GO_VERSION" >> "$GITHUB_OUTPUT"

      - name: Check Go Version
        run: |
          echo "Current version in go.mod is: ${{ steps.get-version.outputs.version }}"

  tests:
    name: go-tests
    needs: [ get-go-version]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ needs.get-go-version.outputs.go_version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.0
          args: --timeout=10m --modules-download-mode=readonly

      - name: sonarcloud-scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  release:
    name: semantic-release
    runs-on: ubuntu-latest
    needs: [ tests ]
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/git@10.0.1
            @semantic-release/exec@6.0.2
            @semantic-release/changelog@6.0.1
