name: Trivy Scan
on:
  pull_request:
jobs:
  trivy_scan:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ "1.16" ]
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Configure ssh-key for private modules
        env:
          SSH_KEY: ${{ secrets.ENGINEERING_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh; echo "$SSH_KEY" > ~/.ssh/id_rsa; chmod 600 ~/.ssh/id_rsa; git config --global url."git@github.com:".insteadOf "https://github.com/"

      - name: Setup go modules
        run: go clean -modcache;go mod tidy; go mod download; go mod verify; go mod vendor;

      - name: Set env
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          echo "VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV

      - name: Build an image from Dockerfile
        env:
          SSH_KEY: ${{ secrets.ENGINEERING_SSH_KEY }}
        run: |
          docker build \
           -t ${{ secrets.GCP_TEST_CONTAINER_REGISTRY_PROJECT_NAME }}/${{ env.REPO_NAME }}:${{ github.sha }} \
           --build-arg SSH_PRIVATE_KEY="${SSH_KEY}" .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ secrets.GCP_TEST_CONTAINER_REGISTRY_PROJECT_NAME }}/${{ env.REPO_NAME }}:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
